export type PublicContentType = "play" | "film" | "video";

export type PublicContentEntry = {
  id: string;
  slug: string;
  type: PublicContentType;
  title: string;
  subtitle: string;
  summary: string;
  tags: string[];
  featured: boolean;
  status: "published" | "coming-soon";
  updatedAt: string;
  durationLabel?: string;
  coverTone: "slate" | "violet" | "cyan" | "amber";
  coverImageUrl: string;
  thumbnailImageUrl?: string;
  primaryActionLabel: string;
  rankScore?: number;
  recentPlayAt?: string;
};

export type PublicSectionMeta = {
  type: PublicContentType;
  title: string;
  description: string;
  ctaLabel: string;
  href: string;
};

export const PUBLIC_SECTIONS: PublicSectionMeta[] = [
  {
    type: "play",
    title: "Play",
    description: "轻量、直接、点开就玩的小游戏集合。",
    ctaLabel: "查看全部可玩内容",
    href: "/play",
  },
  {
    type: "film",
    title: "互动影游",
    description: "更完整的剧情互动体验，强调角色、镜头和分支推进。",
    ctaLabel: "查看全部互动影游",
    href: "/film",
  },
  {
    type: "video",
    title: "视频",
    description: "不要求交互，强调观看效率和内容分发的线性视频。",
    ctaLabel: "查看全部视频",
    href: "/video",
  },
];

export const PUBLIC_CONTENT: PublicContentEntry[] = [
  {
    id: "billionaire-path",
    slug: "billionaire-path",
    type: "play",
    title: "首富人生模拟器",
    subtitle: "从 5 岁到命运副本的改编人生局",
    summary:
      "从童年、异乡打工、职业抉择到中年商战档案，每一关都决定你最后会拿到哪条命运线和哪份终局揭示。",
    tags: ["人生模拟", "章节抉择", "商战档案"],
    featured: true,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "7 抉择",
    coverTone: "amber",
    coverImageUrl: "/covers/play/billionaire-path.svg",
    thumbnailImageUrl: "/covers/play/billionaire-path.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 99,
  },
  {
    id: "click-chase",
    slug: "click-chase",
    type: "play",
    title: "点击追踪",
    subtitle: "追着目标猛点的 25 秒冲刺",
    summary: "目标会不断换位、变速、缩放，考验你的点击节奏和反应速度。",
    tags: ["反应", "点击", "快节奏"],
    featured: true,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "25 秒",
    coverTone: "cyan",
    coverImageUrl: "/covers/play/click-chase.svg",
    thumbnailImageUrl: "/covers/play/click-chase.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 96,
  },
  {
    id: "memory-flip",
    slug: "memory-flip",
    type: "play",
    title: "记忆翻牌",
    subtitle: "最经典的一局记忆挑战",
    summary: "翻开卡面，找到全部配对，尽量用更少步数更快完成。",
    tags: ["记忆", "翻牌", "轻策略"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "1-2 分钟",
    coverTone: "slate",
    coverImageUrl: "/covers/play/memory-flip.svg",
    thumbnailImageUrl: "/covers/play/memory-flip.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 92,
  },
  {
    id: "lane-dodge",
    slug: "lane-dodge",
    type: "play",
    title: "躲避快线",
    subtitle: "三车道躲障碍，坚持越久越高分",
    summary: "用左右切换车道，避免撞上前方落下的障碍。",
    tags: ["躲避", "街机", "反应"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "30 秒",
    coverTone: "amber",
    coverImageUrl: "/covers/play/lane-dodge.svg",
    thumbnailImageUrl: "/covers/play/lane-dodge.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 89,
  },
  {
    id: "signal-sequence",
    slug: "signal-sequence",
    type: "play",
    title: "信号序列",
    subtitle: "记住灯阵顺序，越往后越难",
    summary: "观察闪烁顺序并复现，考验短时记忆和注意力。",
    tags: ["序列", "记忆", "节奏"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "1-3 分钟",
    coverTone: "cyan",
    coverImageUrl: "/covers/play/signal-sequence.svg",
    thumbnailImageUrl: "/covers/play/signal-sequence.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 85,
  },
  {
    id: "crate-sort",
    slug: "crate-sort",
    type: "play",
    title: "货箱分拣",
    subtitle: "把货箱快速分到正确区域",
    summary: "看准颜色和标记，把不同货箱送到正确位置。",
    tags: ["分类", "手速", "操作"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "35 秒",
    coverTone: "amber",
    coverImageUrl: "/covers/play/crate-sort.svg",
    thumbnailImageUrl: "/covers/play/crate-sort.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 83,
  },
  {
    id: "truth-judge",
    slug: "truth-judge",
    type: "play",
    title: "真假判断",
    subtitle: "连续判断线索陈述的真假",
    summary: "在短时间内快速做出判断，维持高连击。",
    tags: ["问答", "判断", "连击"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "12 题",
    coverTone: "slate",
    coverImageUrl: "/covers/play/truth-judge.svg",
    thumbnailImageUrl: "/covers/play/truth-judge.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 81,
  },
  {
    id: "route-planner",
    slug: "route-planner",
    type: "play",
    title: "路线规划",
    subtitle: "选一条最合理的通关路径",
    summary: "在有限步数里穿过障碍，拿到补给并抵达终点。",
    tags: ["路径", "策略", "益智"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "多关卡",
    coverTone: "slate",
    coverImageUrl: "/covers/play/route-planner.svg",
    thumbnailImageUrl: "/covers/play/route-planner.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 80,
  },
  {
    id: "rhythm-gate",
    slug: "rhythm-gate",
    type: "play",
    title: "节奏闸门",
    subtitle: "踩准时机一口气通过闸门",
    summary: "在最佳时机出手，连击越高得分越高。",
    tags: ["节奏", "判定", "街机"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "10 回合",
    coverTone: "cyan",
    coverImageUrl: "/covers/play/rhythm-gate.svg",
    thumbnailImageUrl: "/covers/play/rhythm-gate.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 84,
  },
  {
    id: "harbor-match",
    slug: "harbor-match",
    type: "play",
    title: "港口连线",
    subtitle: "把左右两列正确配对",
    summary: "记住关系，快速完成一轮又一轮匹配。",
    tags: ["匹配", "连线", "轻益智"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "1-2 分钟",
    coverTone: "slate",
    coverImageUrl: "/covers/play/harbor-match.svg",
    thumbnailImageUrl: "/covers/play/harbor-match.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 78,
  },
  {
    id: "code-breaker",
    slug: "code-breaker",
    type: "play",
    title: "密码破译",
    subtitle: "8 次机会猜中 4 位密码",
    summary: "根据反馈调整策略，在有限尝试中破解密码。",
    tags: ["数字", "推理", "逻辑"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "8 次尝试",
    coverTone: "amber",
    coverImageUrl: "/covers/play/code-breaker.svg",
    thumbnailImageUrl: "/covers/play/code-breaker.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 82,
  },
  {
    id: "stack-balance",
    slug: "stack-balance",
    type: "play",
    title: "猪外有猪",
    subtitle: "叠得越稳，越停不下来",
    summary: "看准时机往上叠，越往后越心跳，差一点就倒。",
    tags: ["堆叠", "反应", "近胜利"],
    featured: true,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "10 层",
    coverTone: "amber",
    coverImageUrl: "/covers/play/stack-balance.svg",
    thumbnailImageUrl: "/covers/play/stack-balance.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 98,
  },
  {
    id: "tile-rush",
    slug: "tile-rush",
    type: "play",
    title: "三消急救",
    subtitle: "先轻松，后窒息",
    summary: "只能拿最上层，槽位又少，快一步就顺，慢一步就爆。",
    tags: ["三消", "羊了个羊感", "近胜利"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "1 局",
    coverTone: "violet",
    coverImageUrl: "/covers/play/tile-rush.svg",
    thumbnailImageUrl: "/covers/play/tile-rush.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 94,
  },
  {
    id: "reaction-shot",
    slug: "reaction-shot",
    type: "play",
    title: "瞬时开枪",
    subtitle: "亮灯就打，毫秒决胜",
    summary: "等信号亮起再出手，打早了算犯规，打慢了也会掉分。",
    tags: ["反应", "对决", "社交挑战"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "8 轮",
    coverTone: "cyan",
    coverImageUrl: "/covers/play/reaction-shot.svg",
    thumbnailImageUrl: "/covers/play/reaction-shot.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 91,
  },
  {
    id: "merge-camp",
    slug: "merge-camp",
    type: "play",
    title: "营地合成",
    subtitle: "小合成，也有回流感",
    summary: "回合很短，目标很直，盯着一格一格把营火合上去。",
    tags: ["合成", "轻养成", "回流"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "8 回合",
    coverTone: "amber",
    coverImageUrl: "/covers/play/merge-camp.svg",
    thumbnailImageUrl: "/covers/play/merge-camp.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 90,
  },
  {
    id: "switch-lock",
    slug: "switch-lock",
    type: "play",
    title: "机关锁",
    subtitle: "一步错，整条电路都断",
    summary: "在 9 步之内把电流一路打通到锁芯，越后面越容易手滑。",
    tags: ["机关", "逻辑", "浏览器巧思"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "9 步",
    coverTone: "slate",
    coverImageUrl: "/covers/play/switch-lock.svg",
    thumbnailImageUrl: "/covers/play/switch-lock.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 87,
  },
  {
    id: "perfect-cut",
    slug: "perfect-cut",
    type: "play",
    title: "完美切线",
    subtitle: "卡准那一刀",
    summary: "切线来回摆，准心很窄，越接近中心越爽。",
    tags: ["时机", "判定", "街机"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-14",
    durationLabel: "8 轮",
    coverTone: "slate",
    coverImageUrl: "/covers/play/perfect-cut.svg",
    thumbnailImageUrl: "/covers/play/perfect-cut.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 86,
  },
  {
    id: "midnight-call",
    slug: "midnight-call",
    type: "film",
    title: "午夜来电",
    subtitle: "互动影游案例",
    summary: "一通来电把主角拉回事故夜，玩家通过几个关键选择逐步进入主线。",
    tags: ["剧情互动", "悬疑", "分支"],
    featured: true,
    status: "published",
    updatedAt: "2026-04-08",
    durationLabel: "8-12 分钟",
    coverTone: "cyan",
    coverImageUrl: "/covers/film/midnight-call.svg",
    thumbnailImageUrl: "/covers/film/midnight-call.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 88,
  },
  {
    id: "school-gate",
    slug: "school-gate-promo",
    type: "film",
    title: "校门口的最后十秒",
    subtitle: "校园互动短剧",
    summary: "在一次极短的时间循环里追问到底是谁留在校门口，适合多分支推进。",
    tags: ["校园", "短剧", "互动影游"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-06",
    durationLabel: "6-10 分钟",
    coverTone: "amber",
    coverImageUrl: "/covers/film/school-gate-promo.svg",
    thumbnailImageUrl: "/covers/film/school-gate-promo.svg",
    primaryActionLabel: "开始游玩",
    rankScore: 79,
  },
  {
    id: "cold-freight",
    slug: "cold-freight",
    type: "video",
    title: "冷库追证",
    subtitle: "线性观看版",
    summary: "把核心支线压成单一路径观看版，适合分发和直接观看。",
    tags: ["纯视频", "线性版", "悬疑"],
    featured: true,
    status: "published",
    updatedAt: "2026-04-07",
    durationLabel: "7 分钟",
    coverTone: "slate",
    coverImageUrl: "/covers/video/cold-freight.svg",
    thumbnailImageUrl: "/covers/video/cold-freight.svg",
    primaryActionLabel: "立即观看",
    rankScore: 77,
  },
  {
    id: "tower-night",
    slug: "tower-night",
    type: "video",
    title: "灯塔协定",
    subtitle: "港口夜景短片",
    summary: "更偏氛围与镜头语言的成片化视频，适合纯观看和社媒分发。",
    tags: ["短片", "氛围", "港口"],
    featured: false,
    status: "published",
    updatedAt: "2026-04-05",
    durationLabel: "5 分钟",
    coverTone: "violet",
    coverImageUrl: "/covers/video/tower-night.svg",
    thumbnailImageUrl: "/covers/video/tower-night.svg",
    primaryActionLabel: "立即观看",
    rankScore: 74,
  },
];

export function getSectionMeta(type: PublicContentType) {
  return PUBLIC_SECTIONS.find((section) => section.type === type) ?? PUBLIC_SECTIONS[0];
}

export function getEntriesByType(type: PublicContentType) {
  return PUBLIC_CONTENT.filter((entry) => entry.type === type);
}

export function getFeaturedEntry() {
  return (
    PUBLIC_CONTENT.find((entry) => entry.type === "play" && entry.featured) ??
    PUBLIC_CONTENT[0]
  );
}

export function getTopRankedEntries(type: PublicContentType, limit = 8) {
  return PUBLIC_CONTENT.filter((entry) => entry.type === type)
    .sort((a, b) => (b.rankScore ?? 0) - (a.rankScore ?? 0))
    .slice(0, limit);
}

export function getPublicEntryBySlug(type: PublicContentType, slug: string) {
  return PUBLIC_CONTENT.find((entry) => entry.type === type && entry.slug === slug) ?? null;
}
